//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dsw2026Tpi.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Issue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Issue() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dsw2026Tpi.CrossCutting.Resources.Issue", typeof(Issue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a StartTime debe ser antes que endTime.
        /// </summary>
        public static string DAY_ERROR {
            get {
                return ResourceManager.GetString("DAY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI no corresponde a un paciente registrado..
        /// </summary>
        public static string DNI_NOTFOUND {
            get {
                return ResourceManager.GetString("DNI_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI ya existe en el sistema.
        /// </summary>
        public static string DUPLICATE_DNI {
            get {
                return ResourceManager.GetString("DUPLICATE_DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un medico con la licencia ingresada. Ingrese una distinta..
        /// </summary>
        public static string DUPLICATE_LICENCE {
            get {
                return ResourceManager.GetString("DUPLICATE_LICENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Email no se encontró..
        /// </summary>
        public static string EMAIL_ERROR {
            get {
                return ResourceManager.GetString("EMAIL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID no corresponde a una entidad registrada..
        /// </summary>
        public static string ID_NOTFOUND {
            get {
                return ResourceManager.GetString("ID_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Día no existe..
        /// </summary>
        public static string INVALID_DAY {
            get {
                return ResourceManager.GetString("INVALID_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Descripción es inválida. El campo debe contener entre 10 y 100 números..
        /// </summary>
        public static string INVALID_DESCRIPTION {
            get {
                return ResourceManager.GetString("INVALID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI es inválido. El campo debe contener entre 7 y 8 números..
        /// </summary>
        public static string INVALID_DNI {
            get {
                return ResourceManager.GetString("INVALID_DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del Email no es correcto..
        /// </summary>
        public static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Nombre es inválido. El campo debe contener entre 3 y 100 caracteres..
        /// </summary>
        public static string INVALID_NAME {
            get {
                return ResourceManager.GetString("INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Razón es inválida. El campo debe contener por lo menos 5 caracteres..
        /// </summary>
        public static string INVALID_REASON {
            get {
                return ResourceManager.GetString("INVALID_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Turno no corresponde  a uno ocupado..
        /// </summary>
        public static string NOT_BOOKEDSLOT {
            get {
                return ResourceManager.GetString("NOT_BOOKEDSLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Turno debe corresponder a fechas posteriores a la actual..
        /// </summary>
        public static string NOTACTUAL_SLOT {
            get {
                return ResourceManager.GetString("NOTACTUAL_SLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Turno debe estar disponible..
        /// </summary>
        public static string NOTAVAILABLE_SLOT {
            get {
                return ResourceManager.GetString("NOTAVAILABLE_SLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los horarios no deben coincidir con los ya cargados..
        /// </summary>
        public static string OVERLAP {
            get {
                return ResourceManager.GetString("OVERLAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es incorrecta..
        /// </summary>
        public static string PASSWORD_ERROR {
            get {
                return ResourceManager.GetString("PASSWORD_ERROR", resourceCulture);
            }
        }
    }
}
